#!/bin/sh
# Build VpncBar. Usage: ./build.sh [release|debug|pkg|clean]   (default: release)
# Installation is separate: ./install.sh [release|debug], or for the Arch
# package: sudo pacman -U packaging/arch/vpncbar-*.pkg.tar.zst
set -e
cd "$(dirname "$0")"

# Compress a release binary with UPX when it's available. Skips cleanly if upx
# isn't installed or the binary is already packed. UPX only shrinks the app
# binary itself (the GTK stack is external shared libs, untouched) and the
# binary is decompressed into RAM at startup — so this is a size-only win, and a
# silent no-op on systems without upx.
maybe_upx() {
    bin=$1
    if ! command -v upx >/dev/null 2>&1; then
        echo "==> upx not installed — skipping compression"
        return 0
    fi
    if upx -l "$bin" >/dev/null 2>&1; then
        echo "==> $bin already UPX-packed — skipping"
        return 0
    fi
    echo "==> Compressing $bin with UPX"
    upx -q --best --lzma "$bin" >/dev/null
}

# packaging/arch is fully GENERATED here (and gitignored), so `./build.sh pkg`
# always works even after a `git clean`. Edit this function, not the output.
# pkgver comes from Cargo.toml — single place to bump the version.
write_arch_packaging() {
    PKGVER=$(sed -n 's/^version *= *"\(.*\)"/\1/p' Cargo.toml | head -1)
    mkdir -p packaging/arch
    cat > packaging/arch/PKGBUILD <<'EOF'
# GENERATED by ../../build.sh — edit build.sh, not this file.
# Builds from THIS checkout (local changes included): ./build.sh pkg
# Lives in a subdir so makepkg's src/ and pkg/ staging dirs can't collide
# with the repo's Rust src/.
pkgname=vpncbar
pkgver=@VERSION@
pkgrel=1
pkgdesc="Tray front-end for vpnc (Cisco IPSec) and openconnect (AnyConnect SSL)"
arch=('x86_64')
url="https://github.com/bouncyball-git/vpncbar-linux"
license=('GPL-2.0-or-later')
depends=('gtk4' 'vpnc' 'libsecret' 'polkit')
optdepends=('openconnect: AnyConnect SSL support'
            'gnome-shell-extension-appindicator: system tray icon on GNOME (SNI host)')
makedepends=('rust')
install=vpncbar.install
# Local-tree build: no remote sources; Cargo.lock pins the crates.
source=()
# !strip: cargo already strips (profile.release strip=true), and if we UPX the
# binary below, makepkg's own strip pass would corrupt the packed binary.
options=('!debug' '!strip')

_repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

build() {
    cd "$_repo"
    cargo build --release --locked
}

package() {
    cd "$_repo"
    install -Dm755 target/release/vpncbar           "$pkgdir/usr/bin/vpncbar"
    # Compress the packaged binary with UPX when available (skipped otherwise).
    # Runs on the staged copy, not cargo's output; !strip above keeps makepkg
    # from re-stripping (and corrupting) the packed binary.
    if command -v upx >/dev/null 2>&1; then
        upx -q --best --lzma "$pkgdir/usr/bin/vpncbar" >/dev/null
    fi
    install -Dm755 packaging/vpncbar-setup          "$pkgdir/usr/bin/vpncbar-setup"
    install -Dm755 packaging/vpncbar-script         "$pkgdir/usr/lib/vpncbar/vpncbar-script"
    install -Dm755 packaging/vpncbar-disconnect     "$pkgdir/usr/lib/vpncbar/vpncbar-disconnect"
    # Vendor rules dir (packages use /usr/share, admins use /etc; polkit reads both).
    install -Dm644 packaging/10-vpncbar.rules       "$pkgdir/usr/share/polkit-1/rules.d/10-vpncbar.rules"
    install -Dm644 packaging/io.github.vpncbar.desktop \
        "$pkgdir/usr/share/applications/io.github.vpncbar.desktop"
    install -Dm644 packaging/lock.svg \
        "$pkgdir/usr/share/icons/hicolor/scalable/apps/io.github.vpncbar.svg"
    # Create the passwordless-polkit group at install time (systemd-sysusers).
    install -dm755 "$pkgdir/usr/lib/sysusers.d"
    echo 'g vpncbar -' > "$pkgdir/usr/lib/sysusers.d/vpncbar.conf"
}
EOF
    sed -i "s/@VERSION@/$PKGVER/" packaging/arch/PKGBUILD
    cat > packaging/arch/vpncbar.install <<'EOF'
# Colour only under terminal pacman. GUI installers (pamac) don't render ANSI
# and would show the codes as garbage — detect the invoker via the parent
# process and stay plain there.
_vb_colors() {
    hi= off=
    if [ -r "/proc/$PPID/comm" ] && [ "$(cat /proc/$PPID/comm 2>/dev/null)" = pacman ]; then
        hi=$(printf '\033[1;38;5;208m') # bold orange
        off=$(printf '\033[0m')
    fi
}

post_install() {
    _vb_colors
    cat <<MSG
==> GNOME users: the tray icon needs an SNI host. Install and enable:
        sudo pacman -S gnome-shell-extension-appindicator
    (KDE Plasma, XFCE, Waybar etc. support it out of the box.)

${hi}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  FINALIZE THE INSTALLATION (required) — joins you to the
!!  passwordless 'vpncbar' group, optionally configures split DNS:
!!
!!      sudo vpncbar-setup
!!
!!  then log out/in once (or run: newgrp vpncbar).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!${off}
MSG
}

post_upgrade() {
    true
}

pre_remove() {
    # Undo what vpncbar-setup changed (group memberships it added, DNS), from
    # its recorded state — no-op if nothing was changed. Runs while the script
    # is still installed.
    /usr/bin/vpncbar-setup restore || true
}

post_remove() {
    _vb_colors
    cat <<MSG
${hi}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  Your VPN profiles and stored secrets were KEPT.
!!
!!  For a full wipe:  rm -rf ~/.config/vpncbar  and clear 'vpnc-*'
!!  items from your keyring.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!${off}
MSG
}
EOF
}

usage() {
    cat <<EOF
Usage: $0 [release|debug|pkg|clean|usage]

  release   optimized build (default)        -> target/release/vpncbar
  debug     fast unoptimized build           -> target/debug/vpncbar
  pkg       Arch/Manjaro package via makepkg -> packaging/arch/vpncbar-*.pkg.tar.zst
  clean [what [part]]   remove build artifacts:
                   (none)               -> everything (cargo + packaging)
                   release|debug        -> that profile's whole target dir
                   release|debug deps   -> dependency cache only (keeps binary;
                                           next build recompiles everything)
                   release|debug app    -> app artifacts only (keeps dep cache;
                                           next build is quick)
                   pkg                  -> packaging/arch only
  usage     this help (also: -h, --help, help)

Install afterwards with ./install.sh [release|debug], or for the package:
    sudo pacman -U packaging/arch/vpncbar-*.pkg.tar.zst
EOF
}

PROFILE="${1:-release}"
case "$PROFILE" in
    release | debug) ;;
    usage | help | -h | --help)
        usage
        exit 0
        ;;
    pkg)
        echo "==> Generating packaging/arch (PKGBUILD + .install)"
        write_arch_packaging
        echo "==> Building Arch package (makepkg)"
        cd packaging/arch
        makepkg -f
        echo "Built $(ls -t vpncbar-*.pkg.tar.* | head -1) — install with:"
        echo "    sudo pacman -U packaging/arch/$(ls -t vpncbar-*.pkg.tar.* | head -1)"
        exit 0
        ;;
    clean)
        case "${2:-all}" in
            all)
                echo "==> Cleaning everything (cargo + packaging)"
                cargo clean
                rm -rf packaging/arch
                ;;
            release | debug)
                if [ "$2" = release ]; then
                    DIR=target/release
                    PROF="--release"
                else
                    DIR=target/debug
                    PROF="--profile dev"
                fi
                case "${3:-all}" in
                    all)
                        echo "==> Cleaning all $2 build artifacts"
                        cargo clean $PROF
                        ;;
                    deps)
                        # Drop the dependency cache but KEEP the final binary.
                        # Next build recompiles everything from scratch.
                        echo "==> Cleaning $2 dependency cache (keeping the binary)"
                        rm -rf "$DIR/deps" "$DIR/build" "$DIR/.fingerprint" "$DIR/incremental"
                        ;;
                    app)
                        # Drop only the app's own artifacts; the dependency
                        # cache stays, so the next build is quick.
                        echo "==> Cleaning $2 app artifacts (keeping the dependency cache)"
                        cargo clean $PROF -p vpncbar-linux
                        ;;
                    *)
                        usage >&2
                        exit 1
                        ;;
                esac
                ;;
            pkg)
                echo "==> Cleaning Arch packaging artifacts"
                rm -rf packaging/arch
                ;;
            *)
                usage >&2
                exit 1
                ;;
        esac
        exit 0
        ;;
    *) usage >&2; exit 1 ;;
esac

# gtk4 headers are a build dependency (runtime checks live in install.sh).
if ! pkg-config --exists gtk4 2>/dev/null; then
    echo "gtk4 development files not found."
    echo "On Arch/Manjaro:  sudo pacman -S --needed gtk4"
    exit 1
fi

echo "==> Building $PROFILE binary"
if [ "$PROFILE" = release ]; then
    cargo build --release
    maybe_upx target/release/vpncbar
else
    cargo build
fi

echo "Built target/$PROFILE/vpncbar"
