#!/bin/sh
# Build VpncBar. Usage: ./build.sh [release|debug|pkg|clean]   (default: release)
# Installation is separate: ./install.sh [release|debug], or for the Arch
# package: sudo pacman -U packaging/arch/vpncbar-*.pkg.tar.zst
set -e
cd "$(dirname "$0")"

# packaging/arch is fully GENERATED here (and gitignored), so `./build.sh pkg`
# always works even after a `git clean`. Edit this function, not the output.
# pkgver comes from Cargo.toml — single place to bump the version.
write_arch_packaging() {
    PKGVER=$(sed -n 's/^version *= *"\(.*\)"/\1/p' Cargo.toml | head -1)
    mkdir -p packaging/arch
    cat > packaging/arch/PKGBUILD <<'EOF'
# GENERATED by ../../build.sh — edit build.sh, not this file.
# Builds from THIS checkout (local changes included): ./build.sh pkg
# Lives in a subdir so makepkg's src/ and pkg/ staging dirs can't collide
# with the repo's Rust src/.
pkgname=vpncbar
pkgver=@VERSION@
pkgrel=1
pkgdesc="Tray front-end for vpnc (Cisco IPSec) and openconnect (AnyConnect SSL)"
arch=('x86_64')
url="https://github.com/bouncyball-git/vpncbar-linux"
license=('GPL-2.0-or-later')
depends=('gtk4' 'vpnc' 'libsecret' 'polkit')
optdepends=('openconnect: AnyConnect SSL support'
            'gnome-shell-extension-appindicator: system tray icon on GNOME (SNI host)')
makedepends=('rust')
install=vpncbar.install
# Local-tree build: no remote sources; Cargo.lock pins the crates.
source=()
options=('!debug')

_repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

build() {
    cd "$_repo"
    cargo build --release --locked
}

package() {
    cd "$_repo"
    install -Dm755 target/release/vpncbar           "$pkgdir/usr/bin/vpncbar"
    install -Dm755 packaging/vpncbar-setup          "$pkgdir/usr/bin/vpncbar-setup"
    install -Dm755 packaging/vpncbar-script         "$pkgdir/usr/lib/vpncbar/vpncbar-script"
    install -Dm755 packaging/vpncbar-disconnect     "$pkgdir/usr/lib/vpncbar/vpncbar-disconnect"
    # Vendor rules dir (packages use /usr/share, admins use /etc; polkit reads both).
    install -Dm644 packaging/10-vpncbar.rules       "$pkgdir/usr/share/polkit-1/rules.d/10-vpncbar.rules"
    install -Dm644 packaging/io.github.vpncbar.desktop \
        "$pkgdir/usr/share/applications/io.github.vpncbar.desktop"
    install -Dm644 packaging/lock.svg \
        "$pkgdir/usr/share/icons/hicolor/scalable/apps/io.github.vpncbar.svg"
    # Create the passwordless-polkit group at install time (systemd-sysusers).
    install -dm755 "$pkgdir/usr/lib/sysusers.d"
    echo 'g vpncbar -' > "$pkgdir/usr/lib/sysusers.d/vpncbar.conf"
}
EOF
    sed -i "s/@VERSION@/$PKGVER/" packaging/arch/PKGBUILD
    cat > packaging/arch/vpncbar.install <<'EOF'
post_install() {
    cat <<'MSG'
!! Finalize the installation (required) — joins you to the passwordless
!! 'vpncbar' group and optionally configures split DNS:
!!
!!     sudo vpncbar-setup
!!
!! then log out/in once (or run: newgrp vpncbar).

==> GNOME users: the tray icon needs an SNI host. Install and enable:
        sudo pacman -S gnome-shell-extension-appindicator
    (KDE Plasma, XFCE, Waybar etc. support it out of the box.)
MSG
}

post_upgrade() {
    true
}

pre_remove() {
    # Undo what vpncbar-setup changed (group memberships it added, DNS), from
    # its recorded state — no-op if nothing was changed. Runs while the script
    # is still installed.
    /usr/bin/vpncbar-setup restore || true
}
EOF
}

usage() {
    cat <<EOF
Usage: $0 [release|debug|pkg|clean|usage]

  release   optimized build (default)        -> target/release/vpncbar
  debug     fast unoptimized build           -> target/debug/vpncbar
  pkg       Arch/Manjaro package via makepkg -> packaging/arch/vpncbar-*.pkg.tar.zst
  clean     remove cargo + makepkg build artifacts
  usage     this help (also: -h, --help, help)

Install afterwards with ./install.sh [release|debug], or for the package:
    sudo pacman -U packaging/arch/vpncbar-*.pkg.tar.zst
EOF
}

PROFILE="${1:-release}"
case "$PROFILE" in
    release | debug) ;;
    usage | help | -h | --help)
        usage
        exit 0
        ;;
    pkg)
        echo "==> Generating packaging/arch (PKGBUILD + .install)"
        write_arch_packaging
        echo "==> Building Arch package (makepkg)"
        cd packaging/arch
        makepkg -f
        echo "Built $(ls -t vpncbar-*.pkg.tar.* | head -1) — install with:"
        echo "    sudo pacman -U packaging/arch/$(ls -t vpncbar-*.pkg.tar.* | head -1)"
        exit 0
        ;;
    clean)
        echo "==> Cleaning build artifacts"
        cargo clean
        rm -rf packaging/arch
        exit 0
        ;;
    *) usage >&2; exit 1 ;;
esac

# gtk4 headers are a build dependency (runtime checks live in install.sh).
if ! pkg-config --exists gtk4 2>/dev/null; then
    echo "gtk4 development files not found."
    echo "On Arch/Manjaro:  sudo pacman -S --needed gtk4"
    exit 1
fi

echo "==> Building $PROFILE binary"
if [ "$PROFILE" = release ]; then
    cargo build --release
else
    cargo build
fi

echo "Built target/$PROFILE/vpncbar"
